name: Custom Issue Template

description: A detailed issue template for tracking implementation tasks.

labels:
  - enhancement
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ## 💻 Description
        - ...

  - type: checkboxes
    attributes:
      label: 🎯 Steps to implement
      options:
        - A
        - B

  - type: input
    attributes:
      label: ⌛ Deadline of the Issue
      description: Please provide the deadline in the format DD/MM/YYYY - DD/MM/YYYY [time]

  - type: markdown
    attributes:
      value: |
        <!--- ADDITIONAL SECTIONS -->

        ## Verification steps
        - [ ] A
        - [ ] B

        ## Reviewer
        - X

